# Generated by Django 2.2.7 on 2019-11-18 21:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import main.models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=main.models.generate_short_id,
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.BinaryField()),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
