# Generated by Django 2.2.7 on 2019-11-18 23:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0003_image_format")]

    operations = [
        migrations.AddField(
            model_name="image", name="size", field=models.IntegerField(default=0)
        )
    ]
