# Generated by Django 2.2.7 on 2019-11-18 23:17
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0004_image_size")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="upgraded_until",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        )
    ]
