# Generated by Django 2.2.7 on 2019-11-18 23:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0006_auto_20191118_2324")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        )
    ]
