# Generated by Django 2.2.7 on 2019-11-19 00:04
from django.db import migrations
from django.db import models

import main.models


class Migration(migrations.Migration):
    dependencies = [("main", "0007_image_name")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                db_index=True, default=main.models.generate_moderate_id, max_length=200
            ),
        )
    ]
