# Generated by Django 2.2.7 on 2019-11-19 14:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0008_user_api_key")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_space",
            field=models.PositiveIntegerField(default=524288000),
        )
    ]
