# Generated by Django 2.2.7 on 2019-11-19 16:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_user_storage_space")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail_512",
            field=models.BinaryField(default=b""),
        )
    ]
