# Generated by Django 2.2.7 on 2019-11-20 14:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_image_thumbnail_512")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="storage_space",
            field=models.PositiveIntegerField(default=1073741824),
        )
    ]
