# Generated by Django 2.2.7 on 2019-11-20 15:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0011_auto_20191120_1434")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="views",
            field=models.PositiveIntegerField(default=0),
        )
    ]
