# Generated by Django 2.2.7 on 2019-11-20 15:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0012_image_views")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="processed",
            field=models.BooleanField(
                default=False,
                help_text="Indicate whether this image has been processed (gone through thumbnail generation, rotation, etc) after upload.",
            ),
        )
    ]
