# Generated by Django 2.2.7 on 2019-11-20 15:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0013_image_processed")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="processed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicate whether this image has been processed (gone through thumbnail generation, rotation, etc) after upload.",
            ),
        )
    ]
