# Generated by Django 2.2.7 on 2019-11-21 10:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0015_user_last_payment")]

    operations = [
        migrations.RenameField(model_name="image", old_name="name", new_name="title")
    ]
