# Generated by Django 2.2.7 on 2019-11-22 16:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0016_auto_20191121_1012")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="storage_space",
            field=models.PositiveIntegerField(default=0),
        )
    ]
