# Generated by Django 2.2.7 on 2019-11-22 23:19
from django.db import migrations
from django.db import models

import main.models


class Migration(migrations.Migration):

    dependencies = [("main", "0017_auto_20191122_1636")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                default=main.models.generate_moderate_id, max_length=200, unique=True
            ),
        )
    ]
