# Generated by Django 2.2.7 on 2019-11-23 10:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0018_auto_20191122_2319")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="storage_space",
            field=models.BigIntegerField(default=0),
        )
    ]
