# Generated by Django 2.2.7 on 2019-11-25 00:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0019_auto_20191123_1026")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bonus_space",
            field=models.BigIntegerField(
                default=0,
                help_text="The user's bonus space (persistent, won or given by admins.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="storage_space",
            field=models.BigIntegerField(
                default=0,
                help_text="The user's base storage space (from their payment plan).",
            ),
        ),
    ]
