# Generated by Django 2.2.7 on 2019-11-27 12:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0020_auto_20191125_0021")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
