# Generated by Django 2.2.17 on 2020-12-23 12:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("main", "0021_image_expires")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=200),
        )
    ]
