# Generated by Django 2.2.17 on 2020-12-24 21:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0022_user_stripe_subscription_id")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_active",
            field=models.BooleanField(default=False),
        )
    ]
