# Generated by Django 2.2.17 on 2020-12-24 23:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0023_user_stripe_subscription_active")]

    operations = [
        migrations.RemoveField(model_name="user", name="stripe_subscription_active")
    ]
