# Generated by Django 2.2.18 on 2021-02-15 13:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0024_remove_user_stripe_subscription_active")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="features",
            field=models.CharField(blank=True, max_length=2000),
        )
    ]
