# Generated by Django 4.2.29 on 2026-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_user_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
